// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC3DAtf4ziEYsmEwgLqEN7PX0aUjlre4g',
    appId: '1:658057192207:android:c31d4880d6505be94f147a',
    messagingSenderId: '658057192207',
    projectId: 'korshiles-17d52',
    storageBucket: 'korshiles-17d52.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTt0LCG5W5GbWyfu65r4v3JHfQh9i2MI',
    appId: '1:658057192207:ios:555353fb48d029704f147a',
    messagingSenderId: '658057192207',
    projectId: 'korshiles-17d52',
    storageBucket: 'korshiles-17d52.firebasestorage.app',
    iosBundleId: 'com.korshiles.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWANlffkefusrxrFpzHwMsVHFiyV16UY',
    appId: '1:658057192207:web:4487ed81a5fd4acf4f147a',
    messagingSenderId: '658057192207',
    projectId: 'korshiles-17d52',
    authDomain: 'korshiles-17d52.firebaseapp.com',
    storageBucket: 'korshiles-17d52.firebasestorage.app',
    measurementId: 'G-JFSZQL2QS8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhWANlffkefusrxrFpzHwMsVHFiyV16UY',
    appId: '1:658057192207:web:f906932f84721ba64f147a',
    messagingSenderId: '658057192207',
    projectId: 'korshiles-17d52',
    authDomain: 'korshiles-17d52.firebaseapp.com',
    storageBucket: 'korshiles-17d52.firebasestorage.app',
    measurementId: 'G-T7WP9FS8Z9',
  );
}
