default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_KEY_ID']}.p8"),
      duration: 1200,
      in_house: false
    )

    # Build the app
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        provisioningProfiles: {
          "com.korshiles.app" => "KorshilesProvision"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )

    # Upload to TestFlight
    upload_to_testflight(api_key: api_key)
  end
end