default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      },
    )

    upload_to_testflight
  end
end