default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_KEY_ID']}.p8")
    )

    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic" # Enable automatic signing
      },
      xcargs: "-allowProvisioningUpdates",
      api_key: api_key
    )

    upload_to_testflight
  end
end