name: Deploy to TestFlight

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_APP_ID: com.korshiles.app
      DISTRIBUTION_CERTIFICATE: ${{ secrets.IOS_DISTRIBUTION_P12 }}
      DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
      PROVISIONING_PROFILE: ${{ secrets.IOS_PROFILE_BASE64 }}

    steps:
      - uses: actions/checkout@v4
      - name: List of Xcode versions
        run: ls /Applications | grep Xcode
      - name: Xcode version select
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      - name: Current Xcode version
        run: xcodebuild -version

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - run: |
          flutter clean
          flutter pub get

      # Set up Ruby (for Fastlane)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # Install Bundler & Fastlane
      - name: Install Bundler and Fastlane
        run: |
          cd ios
          gem install bundler
          bundle init || true
          echo 'gem "fastlane"' >> Gemfile
          bundle install

      # Save API Key file for Fastlane
      - name: Save App Store Connect API Key
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "${APP_STORE_CONNECT_API_KEY}" > ~/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_KEY_ID}.p8
    
      # Build and deploy using Fastlane
      - name: Deploy to TestFlight
        run: |
          cd ios
          bundle exec fastlane beta
